version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch 
      - http.host=0.0.0.0 
      - transport.host=127.0.0.1 
      - xpack.security.enabled=false
    volumes:
      - /opt/elasticsearch/data
    ports:
      - 9200:9200
  fuseki:
    build: "./fuseki"
    ports:
     - 3030:3030
    environment:
     - ADMIN_PASSWORD=robot
  qaunibonn:
    build: "."
    ports:
      - 5000:5000
    links:
     - elasticsearch
     - fuseki
